### PR TITLE
Create 2023-09-13

### PR DESCRIPTION
**Pull request by thisispav**

### CODE REVIEW

**Comment by aljazceru** [comment]
@thisispav it would be good to also update Readme wit the link

**Comment by thisispav** [comment]
2023/09/13 11:00 UTC - LSP Spec Meeting
**Transcript:** https://docs.google.com/document/d/1VaFbMRaJFe0MRvYG_xqVL8itBwhe2o3I39sd7TwgQ6Y/edit#heading=h.9t7z5lby09ho
**Recording:** https://drive.google.com/file/d/16Z7d65y6s8gPuYV6Fjb8d_y_2eqDSi2b/view 
**Attendees:** Elias Rohrer, Pavel Nikolov, Severin Bühler, ZmnSCPxj jxPCSnmZ

@aljazceru my bad. Here you are

**Comment by aljazceru** [comment]
@thisispav 

How Readme.md update should look:
**2023-09-13 - LSP Spec Meeting**
https://github.com/BitcoinAndLightningLayerSpecs/meetings/blob/main/2023-09-13.md

and you shoud rename the file to 2023-09-13.**md** to stay consistent

**Comment by aljazceru** [comment]
anyway i see @BitcoinErrorLog  already merged

**Pull request merged**
